name: prod_pipeline
on:
  push:
    paths: "*"
  schedule:
  - cron: 0-29/10 * * * *
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3.4.0
    - name: echo message
      run: echo Building...
      env:
        USER_PASS: "${{ secrets.BUILD_ADMIN_USER_PASS }}"
        USER_NAME: "${{ secrets.BUILD_ADMIN_USER_NAME }}"
  write_results:
    name: write-results
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: checkout
      uses: actions/checkout@v3.4.0
    - uses: DamianReeves/write-file-action@v1.2
      with:
        path: "${{ env.home}}//results.out"
        contents: These are the results.
